# Generated by Django 5.2.3 on 2025-06-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artista_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='artistas_fotos/', verbose_name='Foto'),
        ),
    ]
