# Generated by Django 5.2.3 on 2025-06-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_artista_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='visualizacoes',
            field=models.IntegerField(default=0, verbose_name='Visualizações'),
        ),
        migrations.AddField(
            model_name='serie',
            name='visualizacoes',
            field=models.IntegerField(default=0, verbose_name='Visualizações'),
        ),
    ]
