# Generated by Django 5.2.3 on 2025-06-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_filme_visualizacoes_serie_visualizacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='link_assistir',
            field=models.URLField(blank=True, null=True, verbose_name='Link para Assistir'),
        ),
    ]
